FROM python:3-slim

WORKDIR /app

COPY requirements.txt /app

RUN pip3 install -r /app/requirements.txt --no-cache-dir

COPY api_referral/ /app/

CMD ["gunicorn", "api_referral.wsgi:application", "--bind", "0:8001"]
