version: '3.8'
services:
  db_api:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - api_db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: denisktv/api_referral:latest
    restart: always
    volumes:
      - api_static_value:/app/static/
      - api_media_value:/app/media/
    depends_on:
      - db_api
    env_file:
      - ./.env

  nginx_api:
    image: nginx:1.19.3-alpine
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - api_static_value:/var/html/static/
      - api_media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  api_static_value:
  api_media_value:
  api_db_value: